FROM golang:1.16-buster

# Install tools
RUN apt-get update \
    && apt-get -y -f dist-upgrade \
    && apt-get install -y -f \
        vim \
        git \
        file \
    && apt-get clean -y

RUN echo "set encoding=utf-8" >> /root/.vimrc \
  && echo "set fileencodings=utf-8" >> /root/.vimrc
